src/Entity/Report.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReportRepository")
 */
class Report
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ebs_splitting;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ebs_posting;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ebs_arbs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prestige_splitting;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prestige_posting;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prestige_arbs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $outcome_assessments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cure_md;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hb_arbs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hb_litigations;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hb_verification_requests;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hb_denials;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hb_initiation_letters;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $jason_gallinna_splitting;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $metro_arbs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $metro_mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $other;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $other_time;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $reportDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEbsSplitting(): ?int
    {
        return $this->ebs_splitting;
    }

    public function setEbsSplitting(?int $ebs_splitting): self
    {
        $this->ebs_splitting = $ebs_splitting;

        return $this;
    }

    public function getEbsPosting(): ?int
    {
        return $this->ebs_posting;
    }

    public function setEbsPosting(?int $ebs_posting): self
    {
        $this->ebs_posting = $ebs_posting;

        return $this;
    }

    public function getEbsArbs(): ?int
    {
        return $this->ebs_arbs;
    }

    public function setEbsArbs(?int $ebs_arbs): self
    {
        $this->ebs_arbs = $ebs_arbs;

        return $this;
    }

    public function getPrestigeSplitting(): ?int
    {
        return $this->prestige_splitting;
    }

    public function setPrestigeSplitting(?int $prestige_splitting): self
    {
        $this->prestige_splitting = $prestige_splitting;

        return $this;
    }

    public function getPrestigePosting(): ?int
    {
        return $this->prestige_posting;
    }

    public function setPrestigePosting(?int $prestige_posting): self
    {
        $this->prestige_posting = $prestige_posting;

        return $this;
    }

    public function getPrestigeArbs(): ?int
    {
        return $this->prestige_arbs;
    }

    public function setPrestigeArbs(?int $prestige_arbs): self
    {
        $this->prestige_arbs = $prestige_arbs;

        return $this;
    }

    public function getOutcomeAssessments(): ?int
    {
        return $this->outcome_assessments;
    }

    public function setOutcomeAssessments(?int $outcome_assessments): self
    {
        $this->outcome_assessments = $outcome_assessments;

        return $this;
    }

    public function getCureMd(): ?int
    {
        return $this->cure_md;
    }

    public function setCureMd(?int $cure_md): self
    {
        $this->cure_md = $cure_md;

        return $this;
    }

    public function getHbArbs(): ?int
    {
        return $this->hb_arbs;
    }

    public function setHbArbs(?int $hb_arbs): self
    {
        $this->hb_arbs = $hb_arbs;

        return $this;
    }

    public function getHbLitigations(): ?int
    {
        return $this->hb_litigations;
    }

    public function setHbLitigations(?int $hb_litigations): self
    {
        $this->hb_litigations = $hb_litigations;

        return $this;
    }

    public function getHbVerificationRequests(): ?int
    {
        return $this->hb_verification_requests;
    }

    public function setHbVerificationRequests(?int $hb_verification_requests): self
    {
        $this->hb_verification_requests = $hb_verification_requests;

        return $this;
    }

    public function getHbDenials(): ?int
    {
        return $this->hb_denials;
    }

    public function setHbDenials(?int $hb_denials): self
    {
        $this->hb_denials = $hb_denials;

        return $this;
    }

    public function getHbInitiationLetters(): ?int
    {
        return $this->hb_initiation_letters;
    }

    public function setHbInitiationLetters(?int $hb_initiation_letters): self
    {
        $this->hb_initiation_letters = $hb_initiation_letters;

        return $this;
    }

    public function getJasonGallinnaSplitting(): ?int
    {
        return $this->jason_gallinna_splitting;
    }

    public function setJasonGallinnaSplitting(?int $jason_gallinna_splitting): self
    {
        $this->jason_gallinna_splitting = $jason_gallinna_splitting;

        return $this;
    }

    public function getMetroArbs(): ?int
    {
        return $this->metro_arbs;
    }

    public function setMetroArbs(?int $metro_arbs): self
    {
        $this->metro_arbs = $metro_arbs;

        return $this;
    }

    public function getMetroMail(): ?int
    {
        return $this->metro_mail;
    }

    public function setMetroMail(?int $metro_mail): self
    {
        $this->metro_mail = $metro_mail;

        return $this;
    }

    public function getOther(): ?string
    {
        return $this->other;
    }

    public function setOther(?string $other): self
    {
        $this->other = $other;

        return $this;
    }

    public function getOtherTime(): ?int
    {
        return $this->other_time;
    }

    public function setOtherTime(?int $other_time): self
    {
        $this->other_time = $other_time;

        return $this;
    }

    public function getReportDate(): ?\DateTimeInterface
    {
        return $this->reportDate;
    }

    public function setReportDate(?\DateTimeInterface $reportDate): self
    {
        $this->reportDate = $reportDate;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

}

src/Form/ReportType.php
<?php

namespace App\Form;

use App\Entity\Report;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ebs_splitting')
            ->add('ebs_posting')
            ->add('ebs_arbs')
            ->add('prestige_splitting')
            ->add('prestige_posting')
            ->add('prestige_arbs')
            ->add('outcome_assessments')
            ->add('cure_md')
            ->add('hb_arbs')
            ->add('hb_litigations')
            ->add('hb_verification_requests')
            ->add('hb_denials')
            ->add('hb_initiation_letters')
            ->add('jason_gallinna_splitting')
            ->add('metro_arbs')
            ->add('metro_mail')
            ->add('other')
            ->add('other_time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Report::class,
        ]);
    }
}

src/Controller/ReportController.php
<?php

namespace App\Controller;

use App\Entity\Report;
use App\Entity\User;
use App\Form\ReportType;
use App\Repository\ReportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/report")
 */
class ReportController extends AbstractController
{

    /**
     * @Route("/", name="report_index", methods={"GET"})
     */
    public function index(Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        if (isset($_GET['fromDate']) && isset($_GET['toDate'])){
            $fromDate = $_GET['fromDate'];
            $toDate = $_GET['toDate'];
            var_dump($fromDate);
            var_dump($toDate);
            $fromDate = strtotime($fromDate);
            $toDate = strtotime($toDate);
            $em = $this->getDoctrine()->getManager();
            $reportRepository = $em->getRepository('App:Report')->createQueryBuilder('r')
                ->where('r.reportDate >= :date')
                ->andWhere("r.reportDate < :date2")
                ->setParameter('date', (date("Y-m-d",$fromDate)))
                ->setParameter('date2', (date("Y-m-d",$toDate)))
                ->getQuery()
                ->getResult();
            $users = $em->getRepository('App:User')->createQueryBuilder('u')
                ->getQuery()
                ->getResult();;

            return $this->render('report/index_by_user.html.twig', [
                'reports' => $reportRepository,
                'users' => $users,
                'fromDate' => $fromDate,
                'toDate' => $toDate,
            ]);
        }else{
            $reportRepository = $em->getRepository('App:Report')->createQueryBuilder('r')
                ->getQuery()
                ->getResult();
            $users = $this->getDoctrine()
                ->getRepository(User::class)
                ->findAll();
            return $this->render('report/index_by_user.html.twig', [
                'reports' => $reportRepository,
                'users' => $users,

            ]);
        }

    }



    /**
     * @Route("/all", name="report_all_reports", methods={"GET"})
     */
    public function indexAll(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $reportRepository = $em->getRepository('App:Report')->createQueryBuilder('r')
            ->getQuery()
            ->getResult();

        return $this->render('report/index.html.twig', [
            'reports' => $reportRepository,
        ]);
    }



    /**
     * @Route("/new", name="report_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $report = new Report();
        $form = $this->createForm(ReportType::class, $report);
        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $report->setReportdate(\DateTime::createFromFormat('m-d-Y', date("m-d-Y")));
            $user = $this->container->get('security.token_storage')->getToken()->getUser();
            $report->setUserId($user);
            $entityManager->persist($report);
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Report created'
            );

            return $this->redirectToRoute('report_index');
        }

        return $this->render('report/new.html.twig', [
            'report' => $report,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="report_show", methods={"GET"})
     */
    public function show(Report $report): Response
    {
        return $this->render('report/show.html.twig', [
            'report' => $report,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="report_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Report $report): Response
    {
        $form = $this->createForm(ReportType::class, $report);
        $form->handleRequest($request);
        $reportdate = $report->getReportdate();

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash(
                'notice',
                'Report created'
            );
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('report_all_reports', [
                'id' => $report->getId(),
            ]);
        }

        return $this->render('report/edit.html.twig', [
            'report' => $report,
            'form' => $form->createView(),
            'reportdate' => $reportdate,
        ]);
    }

    /**
     * @Route("/{id}", name="report_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Report $report): Response
    {
        if ($this->isCsrfTokenValid('delete'.$report->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($report);
            $entityManager->flush();
        }

        return $this->redirectToRoute('report_index');
    }
}

templates/report/_delete_form.html.twig
<form method="post" action="{{ path('report_delete', {'id': report.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ report.id) }}">
    <button class="btn">Delete</button>
</form>

templates/report/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Report{% endblock %}

{% block body %}
    <div class="ui horizontal divider">Edit Report from {{ reportdate|date("m/d/Y") }}</div>

    {{ include('report/_form.html.twig', {'button_label': 'Update'}) }}

    {#<a href="{{ path('report_index') }}">back to list</a>#}

    {#{{ include('report/_delete_form.html.twig') }}#}
{% endblock %}

templates/report/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Report index{% endblock %}

{% block body %}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
    <div class="ui horizontal divider">Report index</div>
    <div class="container">
        <div class="content">
            <table class="ui celled table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>User</th>
                    <th>EBS - Splitting</th>
                    <th>EBS - Posting</th>
                    <th>EBS - Arbs</th>
                    <th>Prestige - Splitting</th>
                    <th>Prestige - Posting</th>
                    <th>Prestige - Arbs</th>
                    <th>Outcome Assessments</th>
                    <th>Cure MD</th>
                    <th>HB - Arbs</th>
                    <th>HB - litigations</th>
                    <th>HB - Verification Request</th>
                    <th>HB - Denials</th>
                    <th>HB - Initiation Letters</th>
                    <th>Jason Gallinna - Splitting</th>
                    <th>Metro - Arbs</th>
                    <th>Metro - Mail</th>
                    <th>Other</th>
                    {#<th>Other Hours</th>#}
                    <th>date</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for report in reports %}
                    <tr>
                        <td>{{ report.id }}</td>
                        <td>{{ report.userId }}</td>
                        <td>{{ report.ebsSplitting }}</td>
                        <td>{{ report.ebsPosting }}</td>
                        <td>{{ report.ebsArbs }}</td>
                        <td>{{ report.prestigeSplitting }}</td>
                        <td>{{ report.prestigePosting }}</td>
                        <td>{{ report.prestigeArbs }}</td>
                        <td>{{ report.outcomeAssessments }}</td>
                        <td>{{ report.cureMd }}</td>
                        <td>{{ report.hbArbs }}</td>
                        <td>{{ report.hbLitigations }}</td>
                        <td>{{ report.hbVerificationRequests }}</td>
                        <td>{{ report.hbDenials }}</td>
                        <td>{{ report.hbInitiationLetters }}</td>
                        <td>{{ report.jasonGallinnaSplitting }}</td>
                        <td>{{ report.metroArbs }}</td>
                        <td>{{ report.metroMail }}</td>
                        <td>
                            {% if report.other is defined and report.otherTime %}
                                {{ report.other }} - {{ report.otherTime }}
                            {% endif %}
                        </td>
                        <td>{{ report.Reportdate|date("m/d/Y") }}</td>
                        {#<td>{{ report.otherTime }}</td>#}
                        <td>
                            <a href="{{ path('report_show', {'id': report.id}) }}">show</a>
                            {% if is_granted('ROLE_SUPER_ADMIN') %}
                                <a href="{{ path('report_edit', {'id': report.id}) }}">edit</a>
                            {% elseif is_granted('ROLE_ADMIN') %}
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="20">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="ui buttons right floated">
                <a class="ui positive center button btn" href="{{ path('report_new') }}">Create new</a>
            </div>
        </div>
    </div>


{% endblock %}

templates/report/index_by_user.html.twig
{% extends 'base.html.twig' %}
{% block title %}Report index{% endblock %}
{% block body %}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
    <div class="ui horizontal divider">Report</div>
    {#<form name="reportDate" method="post">#}
    <form name="" method="GET">
        <label for="fromDate">from</label>
        <input type="date" id="fromDate" name="fromDate">
        <label for="toDate">to</label>
        <input type="date" id="toDate" name="toDate">
        <button type="submit"  id="sbmt-btn">submit</button>
    </form>
    {#{% if fromDate is defined %}#}
        {#fromDate -  {{ fromDate }}#}
    {#{% endif %}#}
    {#{% if toDate is defined %}#}
        {#toDate - {{ toDate }}#}
    {#{% endif %}#}

    <table class="ui celled table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>EBS - Splitting</th>
            <th>EBS - Posting</th>
            <th>EBS - Arbs</th>
            <th>Prestige - Splitting</th>
            <th>Prestige - Posting</th>
            <th>Prestige - Arbs</th>
            <th>Outcome Assessments</th>
            <th>Cure MD</th>
            <th>HB - Arbs</th>
            <th>HB - litigations</th>
            <th>HB - Verification Request</th>
            <th>HB - Denials</th>
            <th>HB - Initiation Letters</th>
            <th>Jason Gallinna - Splitting</th>
            <th>Metro - Arbs</th>
            <th>Metro - Mail</th>
            {#<th>Other</th>#}
            {#<th>date</th>#}
            {#<th>actions</th>#}
        </tr>
        </thead>
        <tbody>




        {% set ebsSplitting = 0 %}
        {% set ebsPosting = 0 %}
        {% set ebsArbs = 0 %}
        {% set prestigeSplitting = 0 %}
        {% set prestigePosting = 0 %}
        {% set prestigeArbs = 0 %}
        {% set outcomeAssessments = 0 %}
        {% set cureMd = 0 %}
        {% set hbArbs = 0 %}
        {% set hbLitigations = 0 %}
        {% set hbVerificationRequests = 0 %}
        {% set hbDenials = 0 %}
        {% set hbInitiationLetters = 0 %}
        {% set jasonGallinnaSplitting = 0 %}
        {% set metroArbs = 0 %}
        {% set metroMail = 0 %}
        {% for user in users %}
            {% set ebsSplitting = 0 %}
            {% set ebsPosting = 0 %}
            {% set ebsArbs = 0 %}
            {% set prestigeSplitting = 0 %}
            {% set prestigePosting = 0 %}
            {% set prestigeArbs = 0 %}
            {% set outcomeAssessments = 0 %}
            {% set cureMd = 0 %}
            {% set hbArbs = 0 %}
            {% set hbLitigations = 0 %}
            {% set hbVerificationRequests = 0 %}
            {% set hbDenials = 0 %}
            {% set hbInitiationLetters = 0 %}
            {% set jasonGallinnaSplitting = 0 %}
            {% set metroArbs = 0 %}
            {% set metroMail = 0 %}
            {% for report in reports %}
                {% if user == report.userId %}
                    {#{% if fromDate is defined and toDate is defined %}#}
                        {#{% if report.date >= fromDate and report.date <= toDate %}#}
                            {% set ebsSplitting = ebsSplitting + report.ebsSplitting %}
                            {% set ebsPosting   = ebsPosting   + report.ebsPosting %}
                            {% set ebsArbs = ebsArbs + report.ebsArbs %}
                            {% set prestigeSplitting = prestigeSplitting + report.prestigeSplitting %}
                            {% set prestigePosting = prestigePosting + report.prestigePosting %}
                            {% set prestigeArbs = prestigeArbs + report.prestigeArbs %}
                            {% set outcomeAssessments = outcomeAssessments + report.outcomeAssessments %}
                            {% set cureMd = cureMd + report.cureMd %}
                            {% set hbArbs = hbArbs + report.hbArbs %}
                            {% set hbLitigations = hbLitigations + report.hbLitigations %}
                            {% set hbVerificationRequests = hbVerificationRequests + report.hbVerificationRequests %}
                            {% set hbDenials = hbDenials + report.hbDenials %}
                            {% set hbInitiationLetters = hbInitiationLetters + report.hbInitiationLetters %}
                            {% set jasonGallinnaSplitting = jasonGallinnaSplitting + report.jasonGallinnaSplitting %}
                            {% set metroArbs = metroArbs + report.metroArbs %}
                            {% set metroMail = metroMail + report.metroMail %}
                        {#{% endif %}#}
                    {#{% endif %}#}

                    {#{% set ebsSplitting = ebsSplitting + report.ebsSplitting %}#}
                    {#{% set ebsPosting   = ebsPosting   + report.ebsPosting %}#}
                    {#{% set ebsArbs = ebsArbs + report.ebsArbs %}#}
                    {#{% set prestigeSplitting = prestigeSplitting + report.prestigeSplitting %}#}
                    {#{% set prestigePosting = prestigePosting + report.prestigePosting %}#}
                    {#{% set prestigeArbs = prestigeArbs + report.prestigeArbs %}#}
                    {#{% set outcomeAssessments = outcomeAssessments + report.outcomeAssessments %}#}
                    {#{% set cureMd = cureMd + report.cureMd %}#}
                    {#{% set hbArbs = hbArbs + report.hbArbs %}#}
                    {#{% set hbLitigations = hbLitigations + report.hbLitigations %}#}
                    {#{% set hbVerificationRequests = hbVerificationRequests + report.hbVerificationRequests %}#}
                    {#{% set hbDenials = hbDenials + report.hbDenials %}#}
                    {#{% set hbInitiationLetters = hbInitiationLetters + report.hbInitiationLetters %}#}
                    {#{% set jasonGallinnaSplitting = jasonGallinnaSplitting + report.jasonGallinnaSplitting %}#}
                    {#{% set metroArbs = metroArbs + report.metroArbs %}#}
                    {#{% set metroMail = metroMail + report.metroMail %}#}
                {% endif %}
            {% endfor %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ ebsSplitting }}</td>
                <td>{{ ebsPosting }}</td>
                <td>{{ ebsArbs }}</td>
                <td>{{ prestigeSplitting }}</td>
                <td>{{ prestigePosting }}</td>
                <td>{{ prestigeArbs }}</td>
                <td>{{ outcomeAssessments }}</td>
                <td>{{ cureMd }}</td>
                <td>{{ hbArbs }}</td>
                <td>{{ hbLitigations }}</td>
                <td>{{ hbVerificationRequests }}</td>
                <td>{{ hbDenials }}</td>
                <td>{{ hbInitiationLetters }}</td>
                <td>{{ jasonGallinnaSplitting }}</td>
                <td>{{ metroArbs }}</td>
                <td>{{ metroMail }}</td>
                {#{% for report in reports %}#}
                    {#<td>{{ report.date|date("m/d/Y") }}</td>#}
                    {#<td>action</td>#}
                    {#<td>action</td>#}
                {#{% endfor %}#}
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="ui buttons right floated">
        <a class="ui positive center button btn" href="{{ path('report_new') }}">Create new</a>
    </div>

{% endblock %}

templates/report/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Report{% endblock %}

{% block body %}
    <div class="ui horizontal divider">Create New Report</div>
    {{ include('report/_form.html.twig') }}

    {#<a href="{{ path('report_index') }}">back to list</a>#}
{% endblock %}

templates/report/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Report{% endblock %}

{% block body %}
<div class="ui form mini form-bacground">
    <div class="content">
        <div class="description">
            <div class="six diagnosis fields">
                <div class="field">
                    <h1>Report</h1>
                    <div class="ui horizontal divider">
                        <table class="ui table">
                            <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ report.id }}</td>
                            </tr>
                            <tr>
                                <th>Ebs_splitting</th>
                                <td>{{ report.ebsSplitting }}</td>
                            </tr>
                            <tr>
                                <th>Ebs_posting</th>
                                <td>{{ report.ebsPosting }}</td>
                            </tr>
                            <tr>
                                <th>Ebs_arbs</th>
                                <td>{{ report.ebsArbs }}</td>
                            </tr>
                            <tr>
                                <th>Prestige_splitting</th>
                                <td>{{ report.prestigeSplitting }}</td>
                            </tr>
                            <tr>
                                <th>Prestige_posting</th>
                                <td>{{ report.prestigePosting }}</td>
                            </tr>
                            <tr>
                                <th>Prestige_arbs</th>
                                <td>{{ report.prestigeArbs }}</td>
                            </tr>
                            <tr>
                                <th>Outcome_assessments</th>
                                <td>{{ report.outcomeAssessments }}</td>
                            </tr>
                            <tr>
                                <th>Cure_md</th>
                                <td>{{ report.cureMd }}</td>
                            </tr>
                            <tr>
                                <th>Hb_arbs</th>
                                <td>{{ report.hbArbs }}</td>
                            </tr>
                            <tr>
                                <th>Hb_litigations</th>
                                <td>{{ report.hbLitigations }}</td>
                            </tr>
                            <tr>
                                <th>Hb_verification_requests</th>
                                <td>{{ report.hbVerificationRequests }}</td>
                            </tr>
                            <tr>
                                <th>Hb_denials</th>
                                <td>{{ report.hbDenials }}</td>
                            </tr>
                            <tr>
                                <th>Hb_initiation_letters</th>
                                <td>{{ report.hbInitiationLetters }}</td>
                            </tr>
                            <tr>
                                <th>Jason_gallinna_splitting</th>
                                <td>{{ report.jasonGallinnaSplitting }}</td>
                            </tr>
                            <tr>
                                <th>Metro_arbs</th>
                                <td>{{ report.metroArbs }}</td>
                            </tr>
                            <tr>
                                <th>Metro_mail</th>
                                <td>{{ report.metroMail }}</td>
                            </tr>
                            <tr>
                                <th>Other</th>
                                <td>{{ report.other }}</td>
                            </tr>
                            <tr>
                                <th>Other_time</th>
                                <td>{{ report.otherTime }}</td>
                            </tr>
                            </tbody>
                        </table>

                        <a href="{{ path('report_index') }}">back to list</a>

                        <a href="{{ path('report_edit', {'id': report.id}) }}">edit</a>

                        {{ include('report/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>




</div>

{% endblock %}